### ISSUE TITLE
GPL licence or at least indication?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaPsychometricsBazzar/RIrtWrappers.jl#6]
I don't know if the wrapped package is GPL, it would still be allowed to have the wrapper MIT. But it would be nice to know and document GPL software is used.

If not for the package itself, then RCall.jl used R of course and it is GPL, so whoever uses your wrapper is bound by the GPL (unless possibly if preinstalled R, because of system library loophole, that wouldn't apply if you were to distribute all including R to users).

RCall.jl should likely document too. What do you think? But should all wrappers for R code, i.e. using it too?

**Comment by frankier** [comment]
Thanks for bringing this up. My opinion is that the best thing is to as far as possible prevent license proliferation in the Julia ecosystem, while making sure to be fair that users are aware of possible legal implications.

I'm a bit unclear on this to be honest. People tend to tie themselves in knots a bit interpreting the GPL, and the way software is distributed and linked has moved on a bit since the early versions were written. The purpose of this package is not so much to have users integrate these libraries into a final Julia project, but rather mainly to make comparisons and demos easier, i.e. it should usually be an optional dependency. It should be flagged up here, but also definitely in RCall.jl. It is linking to R one way or another, and it's not like there is a non-GPL, so it should also be flagged up there.

I'm a bit confused by the system library loophole, but this seems to be more about allowing GPL software to call propriety code e.g. WIN32 APIs. In terms of loophole, it's always temping to go a bit zen and make odd arguments like "I didn't distribute a bundle, but Pkg() did all the fetching and the Julia runtime did the linking on the user's private machine -- nothing to do with me gov'ner" as a loophole. Not sure how that would stand up though -- perhaps not so well.

I think, since only source code is being distributed here, continuing with the current license, but putting a warning should be sufficient. Would you like to make an issue with RCall.jl too or should I? Ideally I would like to have a harmonized approach.

**Comment by frankier** [comment]
Happy to receive comments: https://github.com/JuliaPsychometricsBazzar/RIrtWrappers.jl/commit/b938f394eed2f574b395c8ea80c09b42349ea9ee

**Comment by PallHaraldsson** [comment]
You're right, I misremembered, the system library is about it's explicitly ok to use proprietary system libraries. It's also ok to do whatever in private (that includes companies) with GPL (according to the FSF) with GPL software (same doesn't always apply with APL, or if you use it with a public frontend), such as using with proprietary in case you just don't distribute.

**Comment by PallHaraldsson** [comment]
I see the situation is even more intriguing, since you have GPLv3, which is incompatible with GPLv2 (unless you allow the upgrade option for the whole). I do not see it's "GPL-2.0-only", unlike for this here which is (also BSD):

https://github.com/conda-forge/r-kernsmoothirt-feedstock

Again, whatever you do in private is ok.

**Comment by frankier** [comment]
I'm satisfied that I've addressed that problem as well as possible. To avoid legal problem, nobody should create any composite works with this library without stripping one or the other R dependency if they want to avoid possible technical legal issues. I am of the position that since I am distributing only this source code, I am not creating a composite work. However, I do not see anything like this going to court.

I'm closing this issue now. Do please either go ahead and create an issue on RCall.jl, or let me know if you would prefer that I do it.
